# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='my_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='their_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
